name: Publish UCVM Docker image

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - make : Go to target site
        run: cd ucvm_v22_7
        shell: bash
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mpihuisu/ucvm_227_ivlsu

      - name: Echo metadata
        run: echo " steps.meta.outputs.tags >> " ${{ steps.meta.outputs.tags }}
        run: echo " steps.meta.outputs.labels >> " ${{ steps.meta.outputs.labels }}
        shell: bash
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
#          push: true
# format, tag:DOCKER-HUB-NAMESPACE/DOCKER-HUB-REPOSITORY:VERSION
          tags: "mpihuisu/ucvm_227_ivlsu:0810"
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}


#    - name: Start SSH via Ngrok
#      if: ${{ success() }}
#      uses: luchihoratiu/debug-via-ssh@main
#      with:
#            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
#            NGROK_TIMEOUT: 3000
#            SSH_PASS: ${{ secrets.NGROK_SECRET }}

